-- Monthly Expense Tracker schema for Supabase PostgreSQL

create table if not exists public.monthly_settings (
  id bigint generated by default as identity primary key,
  month_key text not null unique,
  salary numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  month_key text not null references public.monthly_settings(month_key) on delete cascade,
  account_name text not null,
  opening_balance numeric(12,2) not null default 0,
  sort_order integer not null default 0,
  unique(month_key, account_name)
);

create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  month_key text not null references public.monthly_settings(month_key) on delete cascade,
  investment_name text not null,
  amount numeric(12,2) not null default 0,
  sort_order integer not null default 0,
  unique(month_key, investment_name)
);

create table if not exists public.recoverables (
  id bigint generated by default as identity primary key,
  month_key text not null references public.monthly_settings(month_key) on delete cascade,
  person_name text not null,
  amount numeric(12,2) not null default 0,
  recovered boolean not null default false,
  unique(month_key, person_name)
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  month_key text not null references public.monthly_settings(month_key) on delete cascade,
  category text not null,
  budget numeric(12,2) not null default 0,
  actual numeric(12,2) not null default 0,
  sort_order integer not null default 0,
  unique(month_key, category)
);

create index if not exists idx_bank_accounts_month on public.bank_accounts(month_key);
create index if not exists idx_investments_month on public.investments(month_key);
create index if not exists idx_recoverables_month on public.recoverables(month_key);
create index if not exists idx_expenses_month on public.expenses(month_key);

-- Optional starter data matching the supplied workbook.
insert into public.monthly_settings(month_key, salary)
values ('2026-08', 95000)
on conflict (month_key) do nothing;

insert into public.bank_accounts(month_key, account_name, opening_balance, sort_order)
values
('2026-08', 'CBI', 119000, 1),
('2026-08', 'SBI', 16500, 2),
('2026-08', 'ICICI', 1000, 3)
on conflict (month_key, account_name) do nothing;

insert into public.investments(month_key, investment_name, amount, sort_order)
values
('2026-08', 'Monthly SIP', 12000, 1),
('2026-08', 'Monthly Gold ETF', 1000, 2),
('2026-08', 'PPF Monthly', 500, 3),
('2026-08', 'RD Monthly', 5000, 4),
('2026-08', 'Term Insurance', 0, 5),
('2026-08', 'Health Insurance', 0, 6),
('2026-08', 'Emergency Fund', 0, 7)
on conflict (month_key, investment_name) do nothing;

insert into public.recoverables(month_key, person_name, amount, recovered)
values
('2026-08', 'Shubham', 30000, false),
('2026-08', 'Suryaman', 4300, false),
('2026-08', 'Ankan', 5000, false),
('2026-08', 'Ena', 2000, false),
('2026-08', 'Buton da', 2000, false),
('2026-08', 'Chorda', 20000, false),
('2026-08', 'F&F', 15000, false),
('2026-08', 'Variable', 60000, false)
on conflict (month_key, person_name) do nothing;

insert into public.expenses(month_key, category, budget, actual, sort_order)
values
('2026-08', 'Food', 5000, 3000, 1),
('2026-08', 'Travel', 5000, 2300, 2),
('2026-08', 'Petrol', 2000, 420, 3),
('2026-08', 'Groceries and essentials', 5000, 1600, 4),
('2026-08', 'Skin Care Items', 1500, 650, 5),
('2026-08', 'Shopping', 4000, 2600, 6),
('2026-08', 'Wifi / Mobile Recharge', 1000, 520, 7),
('2026-08', 'Misc.', 1000, 320, 8)
on conflict (month_key, category) do nothing;
